apiVersion: v1
kind: Service
metadata:
  name: hello-node
  namespace: development
spec:
  type: LoadBalancer  
  ports:
  - name: api
    port: 80
    targetPort: 3000
  selector:
    app: hello-node